2025-03-01 13:34:17,228 INFO: Iniciando aplicação de combinações [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:60]
2025-03-01 13:34:20,482 INFO: Iniciando aplicação de combinações [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:60]
2025-03-01 13:34:48,614 INFO: Calculando combinações para números: 0,1,2,3,4,5,6,7,8,9, tamanho: 2 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:94]
2025-03-01 13:34:48,617 INFO: Geradas 99 combinações, 60 após filtrar números > 60 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:130]
2025-03-01 13:34:53,626 INFO: Gerando palpites para a Mega Sena. Total: 10, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:34:53,635 INFO: Gerados 10 palpites em 0.00 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 13:35:01,007 INFO: Gerando palpites para a Mega Sena. Total: 10, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:35:01,013 INFO: Gerados 10 palpites em 0.00 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 13:35:33,650 INFO: Gerando palpites para a Mega Sena. Total: 186, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:35:33,665 INFO: Gerados 186 palpites em 0.01 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 13:35:39,210 INFO: Gerando palpites para a Mega Sena. Total: 186, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:35:39,230 INFO: Gerados 186 palpites em 0.01 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 13:36:11,856 INFO: Gerando palpites para a Mega Sena. Total: 105361, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:36:25,258 INFO: Gerados 105361 palpites em 13.40 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 13:36:58,512 INFO: Gerando palpites para a Mega Sena. Total: 105361, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:37:11,606 INFO: Gerados 105361 palpites em 13.09 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 13:37:28,076 INFO: Gerando palpites para a Mega Sena. Total: 105361, Página: 2, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:37:41,461 INFO: Gerados 105361 palpites em 13.38 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 13:38:07,773 INFO: Gerando palpites para a Mega Sena. Total: 105361, Página: 3, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:305]
2025-03-01 13:38:21,094 INFO: Gerados 105361 palpites em 13.32 segundos [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:333]
2025-03-01 14:09:32,966 INFO: Iniciando aplicação de combinações [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:64]
2025-03-01 14:09:38,582 INFO: Iniciando aplicação de combinações [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:64]
2025-03-01 14:10:02,619 INFO: Calculando combinações para números: 0,1,2,3,4,5,6,7,8,9, tamanho: 2 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:98]
2025-03-01 14:10:02,624 INFO: Geradas 99 combinações, 60 após filtrar números > 60 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:134]
2025-03-01 14:10:20,636 INFO: Gerando palpites para a Mega Sena. Total: 199, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:339]
2025-03-01 14:10:23,199 ERROR: Erro inesperado ao gerar palpites: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mUnknown attribute 'sample' of type Module(<module 'random' from 'C:\\Users\\Marcio Fernando Maia\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\random.py'>)
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py (258)[0m
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m

[0m[1mDuring: Pass nopython_type_inference[0m [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:379]
2025-03-01 14:10:23,214 ERROR: Traceback (most recent call last):
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py", line 354, in gerar_palpites
    palpites = gerar_palpites_mega_sena(combinacoes_formatadas, total_palpites)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py", line 208, in gerar_palpites_mega_sena
    return gerar_palpites_numba(np.array(numeros_disponiveis), total_palpites)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\venv\Lib\site-packages\numba\core\dispatcher.py", line 424, in _compile_for_args
    error_rewrite(e, 'typing')
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\venv\Lib\site-packages\numba\core\dispatcher.py", line 365, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mUnknown attribute 'sample' of type Module(<module 'random' from 'C:\\Users\\Marcio Fernando Maia\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\random.py'>)
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py (258)[0m
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m

[0m[1mDuring: Pass nopython_type_inference[0m
 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:381]
2025-03-01 14:10:25,833 INFO: Gerando palpites para a Mega Sena. Total: 199, Página: 1, Itens: 100 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:339]
2025-03-01 14:10:25,837 ERROR: Erro inesperado ao gerar palpites: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mUnknown attribute 'sample' of type Module(<module 'random' from 'C:\\Users\\Marcio Fernando Maia\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\random.py'>)
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py (258)[0m
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m

[0m[1mDuring: Pass nopython_type_inference[0m [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:379]
2025-03-01 14:10:25,847 ERROR: Traceback (most recent call last):
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py", line 354, in gerar_palpites
    palpites = gerar_palpites_mega_sena(combinacoes_formatadas, total_palpites)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py", line 208, in gerar_palpites_mega_sena
    return gerar_palpites_numba(np.array(numeros_disponiveis), total_palpites)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\venv\Lib\site-packages\numba\core\dispatcher.py", line 424, in _compile_for_args
    error_rewrite(e, 'typing')
  File "J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\venv\Lib\site-packages\numba\core\dispatcher.py", line 365, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mUnknown attribute 'sample' of type Module(<module 'random' from 'C:\\Users\\Marcio Fernando Maia\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\random.py'>)
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m
[0m
[0m[1mDuring: typing of get attribute at J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py (258)[0m
[1m
File "app.py", line 258:[0m
[1mdef gerar_palpites_numba(numeros, total):
    <source elided>
        if len(numeros) >= 6:
[1m            indices = random.sample(range(len(numeros)), 6)
[0m            [1m^[0m[0m

[0m[1mDuring: Pass nopython_type_inference[0m
 [in J:\Meu Drive\ProjetosPython\Loterias\Combinacoes\Combinacao-I\app.py:381]
